from flask import Flask, request, jsonify
import tensorflow as tf
import numpy as np
import joblib
import json

app = Flask(__name__)

# =========================
# LOAD MODEL ARTIFACTS
# =========================
model = tf.keras.models.load_model("patient_risk_model.h5")
scaler = joblib.load("patient_scaler.save")

with open("class_names.json", "r") as f:
    class_names = json.load(f)

feature_order = [
    "avg_hr",
    "max_hr",
    "avg_spo2",
    "min_spo2",
    "avg_temp",
    "max_temp",
    "fall_count",
    "high_hr_count",
    "low_spo2_count",
    "high_temp_count"
]

recommendations = {
    "Generally Stable": "Maintain your current routine and continue monitoring.",
    "Possible Arrhythmia Pattern": "Reduce exertion and consult a doctor if symptoms persist.",
    "Possible Cardiovascular Distress": "Seek immediate medical attention."
}

risk_map = {
    "Generally Stable": "Low Risk",
    "Possible Arrhythmia Pattern": "High Risk",
    "Possible Cardiovascular Distress": "Critical Risk"
}

warning_map = {
    "Generally Stable": "Your weekly readings are mostly within normal range.",
    "Possible Arrhythmia Pattern": "Pattern suggests repeated cardiovascular irregularities.",
    "Possible Cardiovascular Distress": "Model detected a high-risk pattern from the recent readings."
}

@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.get_json()

        values = []
        for key in feature_order:
            values.append(float(data.get(key, 0)))

        X = np.array([values], dtype=np.float32)
        X_scaled = scaler.transform(X)

        probs = model.predict(X_scaled, verbose=0)[0]
        pred_idx = int(np.argmax(probs))
        pred_class = class_names[pred_idx]
        confidence = float(np.max(probs))

        probability_breakdown = {
            class_names[i]: round(float(probs[i]) * 100, 2)
            for i in range(len(class_names))
        }

        return jsonify({
            "success": True,
            "condition_name": pred_class,
            "risk_level": risk_map.get(pred_class, "Unknown"),
            "warning_message": warning_map.get(pred_class, "Prediction generated by TensorFlow model."),
            "recommendation": recommendations.get(pred_class, "Continue monitoring."),
            "confidence": round(confidence * 100, 2),
            "probabilities": probability_breakdown
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)